language: node_js
node_js:
    - 'node'

after_success: npm run coverage

deploy:
    provider: npm
    email: npm.bokub@mail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
        tags: true
